[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run crypto_trading_ui.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
